Init package
PsycleResearch/intl-maintainer pull request #1
Opened 2022-11-24 16:53 UTC by mbaumanndev

2022-11-29 11:16 UTC, H2WO4 reviewed
Il manque quelques commentaires pour expliquer le fonction général du programme
Il faudrait aussi une doc des commandes et leurs paramètres dans le README (un copié-collé du message d'aide est suffisant)

2022-11-29 11:16 UTC, H2WO4 commented on src/commands/update.ts
> +        } catch {}
Ça serait mieux d'au moins mettre un `console.log` pour indiquer l'erreur

2022-11-29 11:16 UTC, H2WO4 commented on src/commands/update.ts
> +export async function extractMessagesFromFile(path: string): Promise<Messages> {
Est-ce que ça va être ensuite étendu ?
Si non, autant faire appel à la fonction directement (à moins que je comprenne mal le mécanisme async/await du TS)

2022-11-29 11:18 UTC, Mindstan requested changes
Pourquoi pas utiliser des ensembles plutôt que des listes ? (si ça existe en TS)

2022-11-29 11:18 UTC, Mindstan commented on src/commands/update.ts
> +                dest !== '' &&
Ce n’est pas redondant avec la  ligne suivante ?

2022-11-29 11:18 UTC, Mindstan commented on src/commands/update.ts
> +        const destination = destinations[i]
Ce n’est pas plutôt `fullDestinations[i]` ?

2022-11-29 11:18 UTC, Mindstan commented on src/commands/update.ts
> +    for (let i = 0; i < fullDestinations.length; i++) {
Au vu de mon commentaire ci-après, pourquoi ne pas prendre directement la valeur plutôt que d’utiliser un index ?

2022-11-29 12:39 UTC, mbaumanndev commented on src/commands/update.ts
> +export async function extractMessagesFromFile(path: string): Promise<Messages> {
C'est plus pour encapsuler la fonction et le changer à un seul endroit (comme plus tard on aura différents utilitaires et options sur l'extraction)

2022-11-30 08:39 UTC, danousna submitted a review, later dismissed

2022-11-30 12:15 UTC, Mindstan approved these changes, later dismissed

2022-12-01 13:42 UTC, merged